# Generated by Django 4.2.11 on 2024-06-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_image_path_alter_post_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
